name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Release
        run: cargo build --release

      - name: Rename binary for Windows
        if: runner.os == 'Windows'
        run: mv target/release/dfa-creator.exe target/release/dfa-creator-${{ github.ref_name }}-windows.exe

      - name: Rename binary for Linux
        if: runner.os == 'Linux'
        run: mv target/release/dfa-creator target/release/dfa-creator-${{ github.ref_name }}-linux

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: dfa-creator-${{ github.ref_name }}-${{ matrix.os }}
          path: target/release/dfa-creator*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Check Release Assets
        run: ls

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dfa-creator-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
