name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Library
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Build Binary
        run: cargo build -F dfac

  wasm-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Build WASM
        run: npm run build
