name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Library
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build Binary
        run: cargo build --bin dfac -F bin-deps
